config/routes.rb
P2::Application.routes.draw do
  root  'static_pages#home'
  match '/blog',    to: 'static_pages#blog',    via: 'get'
  match '/faq',   to: 'static_pages#faq',   via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def faq
  end

  def about
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl used as template
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Blog",    blog_path %></li>
          <li><%= link_to "FAQ", faq_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Page</h1>
<p>This is project 2 for CS369, Made by Erik and Matt</p>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>
<h1>Blog</h1>
<p>No Posts Yet</p>

app/views/static_pages/faq.html.erb
<% provide(:title, 'FAQ') %>
<h1>FAQ</h1>
<p>No Questions Yet</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Project 2 Home!</h1>

  <h2>
    This is the home page for project 2 for CS369, made by Erik and Matt
  </h2>

</div>